### ISSUE TITLE
Post install is failing

### ISSUE THREAD

**Issue by andrew-w-ross** [mjackson/expect-element#2]
Perhaps check in the compiled files as 
`babel ./modules -d lib --stage 0 --loose all --ignore '__tests__'` is failing when I try to install.

**Comment by cameron** [comment]
Same error, full output:

```Shell
> expect-element@1.0.0 postinstall /Users/cam/src/_preact/abcd-app/node_modules/expect-element
> node ./npm-scripts/postinstall.js


> expect-element@1.0.0 build /Users/cam/src/_preact/abcd-app/node_modules/expect-element
> babel ./modules -d lib --stage 0 --loose all --ignore '__tests__'

sh: babel: command not found

npm ERR! expect-element@1.0.0 build: `babel ./modules -d lib --stage 0 --loose all --ignore '__tests__'`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the expect-element@1.0.0 build script.
npm ERR! This is most likely a problem with the expect-element package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel ./modules -d lib --stage 0 --loose all --ignore '__tests__'
npm ERR! You can get their info via:
npm ERR!     npm owner ls expect-element
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/Cellar/nvm/0.7.0/v4.2.2/bin/node" "/Users/cam/src/_preact/abcd-app/node_modules/.bin/npm" "run" "build"
npm ERR! cwd /Users/cam/src/_preact/abcd-app/node_modules/expect-element
npm ERR! node -v v4.2.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/cam/src/_preact/abcd-app/node_modules/expect-element/npm-debug.log
npm ERR! not ok code 0
child_process.js:484
    throw err;
    ^

Error: Command failed: npm run build
    at checkExecSyncError (child_process.js:441:13)
    at execSync (child_process.js:481:13)
    at exec (/Users/cam/src/_preact/abcd-app/node_modules/expect-element/npm-scripts/postinstall.js:5:3)
    at /Users/cam/src/_preact/abcd-app/node_modules/expect-element/npm-scripts/postinstall.js:10:5
    at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/nvm/0.7.0/v4.2.2/bin/node" "/usr/local/opt/nvm/v4.2.2/bin/npm" "install" "expect-element" "--save-dev"
npm ERR! node v4.2.2
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE

npm ERR! expect-element@1.0.0 postinstall: `node ./npm-scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the expect-element@1.0.0 postinstall script 'node ./npm-scripts/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the expect-element package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./npm-scripts/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs expect-element
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls expect-element
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cam/src/_preact/abcd-app/npm-debug.log
```
